import Head from 'next/head'

import TaskManager from '../src/components/task-manager'

import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Redux RTK Query Typescript</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<h1 className="w-full bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500"> Next Redux RTK Query Typescript Tailwind </h1>
    <TaskManager />
    </div>
  )
}
