import Head from 'next/head'
import Image from 'next/image'
import TaskManager from '../src/components/task-manager'

import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Redux RTK Query Typescript</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<h1> Next Redux RTK Query Typescript Tailwind </h1>
    <TaskManager />
    </div>
  )
}
