import Head from 'next/head'
import { Counter } from '../src/components/counter/counter'

import TaskManager from '../src/components/todo/task-manager'

import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className="bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 ">
      <Head>
        <title>Redux RTK Query Typescript</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<h1 className="w-full"> Next Redux RTK Query Typescript Tailwind </h1>
    <div className="p-12 ">
        <Counter />
        <TaskManager />
    </div>
    </div>
  )
}
